### ISSUE TITLE
outdated Docker Images

### ISSUE THREAD

**Issue by ukleeberger** [orange-cloudfoundry/credhub_exporter#86]
Hi Guys,

it seems that the Docker Images are very outdated, see https://hub.docker.com/r/orangeopensource/credhub-exporter/tags

I also can't find any Dockerfile to build it myself.

Am I'm missing something?

Greets
Uli

**Comment by adamspd** [comment]
Hi @gberche-orange and @ukleeberger , we don't explicitly have a dockerfile since as @gberche-orange said we're using a bosh-based deployment of the credhub exporter, but I [tried to create one from scratch](https://github.com/orange-cloudfoundry/credhub_exporter/pull/87) and it seem to work, maybe test it to see if it's worth going forward with.

**Comment by ukleeberger** [comment]
@adamspd thx that is a start for me.
